export const courseCard = [
  {
    id: 1,
    image: '/images/thumb3.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 2,
    image: '/images/thumb4.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 3,
    image: '/images/thumb5.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 4,
    image: '/images/thumb6.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 5,
    image: '/images/thumb7.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 6,
    image: '/images/thumb3.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 7,
    image: '/images/thumb4.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 8,
    image: '/images/thumb5.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 9,
    image: '/images/thumb6.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
  {
    id: 10,
    image: '/images/thumb7.png',
    name: 'Khóa học Frontend từ cơ bản đến nâng cao',
    price: 40,
    salePrice: 10.99,
    authorName: 'Hiếu Hồ',
  },
]
