import axiosClient from '@/api-client/axiosClient'
import { EmptyLayout } from '@/components/layout'
import { AppPropsWithLayout } from '@/models/common'
import theme from '@/provider/ThemeProvider'
import CssBaseline from '@mui/material/CssBaseline'
import { ThemeProvider } from '@mui/material/styles'
import Head from 'next/head'
import { SWRConfig } from 'swr'
import '../styles/globals.css'

// Client-side cache, shared for the whole session of the user in the browser.
// const clientSideEmotionCache = createEmotionCache()

function MyApp({ Component, pageProps }: AppPropsWithLayout) {
  const Layout = Component.Layout ?? EmptyLayout

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Head>
        <title>{pageProps.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SWRConfig value={{ fetcher: (url) => axiosClient.get(url), shouldRetryOnError: false }}>
          <Component {...pageProps} />
        </SWRConfig>
      </Layout>
    </ThemeProvider>
  )
}

export default MyApp
